# Generated by Django 6.0.2 on 2026-06-02 09:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('user_answers', models.JSONField(blank=True, default=dict)),
                ('question_order', models.JSONField(blank=True, default=list)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(choices=[('OS', 'Operating Systems'), ('DBMS', 'Database Management Systems'), ('NETWORKS', 'Computer Networks'), ('DATA_STRUCTURES', 'Data Structures & Algorithms'), ('APTITUDE', 'Quantitative Aptitude'), ('REASONING', 'Reasoning Ability'), ('ENGLISH', 'General English'), ('GK', 'General Knowledge & GK')], max_length=50)),
                ('subtopic', models.CharField(max_length=255)),
                ('question_text', models.TextField()),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
