# Generated by Django 6.0.2 on 2026-06-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='test_mode',
            field=models.CharField(default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='examsession',
            name='test_number',
            field=models.IntegerField(default=1),
        ),
    ]
