# Generated by Django 6.0.2 on 2026-06-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0002_examsession_test_mode_examsession_test_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('OS', 'Operating Systems'), ('DBMS', 'Database Management Systems'), ('NETWORKS', 'Computer Networks'), ('DATA_STRUCTURES', 'Data Structures & Algorithms'), ('COA', 'Computer Organization & Architecture'), ('DIGITAL', 'Digital Logic'), ('SOFTWARE', 'Software Engineering'), ('EMERGING', 'Emerging Tech'), ('APTITUDE', 'Quantitative Aptitude'), ('REASONING', 'Reasoning Ability'), ('ENGLISH', 'General English'), ('GK', 'General Knowledge & GK')], max_length=50),
        ),
    ]
