# Generated by Django 6.0.2 on 2026-06-05 14:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0003_alter_question_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(default='ALL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='examsession',
            name='test_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cbt_app.testpackage'),
        ),
        migrations.AddField(
            model_name='question',
            name='test_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='cbt_app.testpackage'),
        ),
    ]
