# Generated by Django 6.0.2 on 2026-06-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0004_testpackage_examsession_test_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examsession',
            name='test_mode',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='test_number',
        ),
    ]
