# Generated by Django 6.0.2 on 2026-06-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt_app', '0005_remove_examsession_test_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpackage',
            name='marks_per_correct',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='testpackage',
            name='negative_marks',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='total_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
